ogimage:
  build: .
  ports:
    - "3008:3000"
  environment:
    - VIRTUAL_HOST=ogimage.me,www.ogimage.me
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=ogimage.me,www.ogimage.me
    - LETSENCRYPT_EMAIL=benjick@dumfan.net
